### ISSUE TITLE
Graceful YAML errors

### ISSUE THREAD

**Issue by petrbel** [Cognexa/cxtream#42]
An error in YAML config (either syntactical or missing an element) results in a completely useless error:

```
RuntimeError: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
```

We should fix cppyaml so that it at least prints the name of node it tries to access. Or maybe check it manually? Or at least report which c++ line threw this exception.

**Comment by FloopCZ** [comment]
(Unfortunately,) YAML parsing is not a part of `cxtream`. In our project, we usually use `yaml-cpp` for this purpose. If we want this, we have to do one of the following:
- We can use a different library.
- We can fix https://github.com/jbeder/yaml-cpp/issues/423.
- We can wrap the extraction in our own function with descriptive error messages.

**Comment by petrbel** [comment]
I understand, however, we still need to fix it somehow. All of the suggested solutions are fine :)

I think we should reopen this issue unless we decide what to do.

**Comment by FloopCZ** [comment]
I agree that this would be nice to have and fixing it upstream would be my preferred way to do it. The yaml-cpp library is otherwise good and its interface is similar to boost::program_options, which I like. However, I believe this issue should be moved to some project, which actually uses yaml-cpp, which is not cxtream, and then it should be decided by @blazekadam. :-)

**Comment by petrbel** [comment]
done
